import os

INFLUXDB_URL = os.environ.get("INFLUXDB_URL", default=None)
INFLUXDB_TOKEN = os.environ.get("INFLUXDB_TOKEN", default=None)
OVERDUE_PLAYER_TIMEDELTA_S = os.environ.get("OVERDUE_PLAYER_TIMEDELTA_S", default=30)
OVERDUE_PLAYER_REMOVAL_INTERVAL_S = os.environ.get("OVERDUE_PLAYER_REMOVAL_INTERVAL_S", default=15)
UNOBSERVED_GAMES_TIMEDELTA_S = os.environ.get("UNOBSERVED_GAMES_TIMEDELTA_S", default=3600)
UNOBSERVED_GAMES_REMOVE_INTERVAL_S = os.environ.get("UNOBSERVED_GAMES_REMOVE_INTERVAL_S", default=1800)
