POST http://localhost:5000/api/games/0/players
content-type: application/json

{
    "alone": true
}

###

GET http://localhost:5000/api/games/0/state?p_id=1

###

POST http://localhost:5000/api/games/0/shift?p_id=1
content-type: application/json

{
    "location": {
        "row": 0,
        "column": 1
    },
    "leftoverRotation": 180
}

###

POST http://localhost:5000/api/games/0/move?p_id=1
content-type: application/json

{
    "location": {
        "row": 0,
        "column": 0
    }
}

###

GET http://localhost/api/games/0/state?p_id=1
