""" A definition of names used as keys in JSON-ready dictionaries """

PLAYERS = "players"
MAZE_CARDS = "mazeCards"
ID = "id"
MAZE_CARD_ID = "mazeCardId"
DOORS = "doors"
LOCATION = "location"
ROTATION = "rotation"
ROW = "row"
COLUMN = "column"
LEFTOVER_ROTATION = "leftoverRotation"
KEY = "key"
MESSAGE = "userMessage"
OBJECTIVE = "objectiveMazeCardId"
NEXT_ACTION = "nextAction"
ACTION = "action"
PLAYER_ID = "playerId"
ALGORITHM = "algorithm"
IS_COMPUTER = "isComputerPlayer"
SHIFT_URL = "shiftApiUrl"
MOVE_URL = "moveApiUrl"
POST_PLAYER_ALONE = "alone"
POST_PLAYER_TYPE = "type"
